// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsiHVaFn1rXwv09czory61cuAn0Ogz_bQ',
    appId: '1:362854059464:web:c02b9bf4248b1165c2c4fd',
    messagingSenderId: '362854059464',
    projectId: 'mimi-5d20c',
    authDomain: 'mimi-5d20c.firebaseapp.com',
    storageBucket: 'mimi-5d20c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxCoLbKd8z3bHiRFrp6KjivqKSqPNHH8',
    appId: '1:362854059464:android:78d6d65901ab433fc2c4fd',
    messagingSenderId: '362854059464',
    projectId: 'mimi-5d20c',
    storageBucket: 'mimi-5d20c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDinjzZv4j0z-IbUz5Vvu37Phc3uREYIdA',
    appId: '1:362854059464:ios:b2a8f907b57c037ac2c4fd',
    messagingSenderId: '362854059464',
    projectId: 'mimi-5d20c',
    storageBucket: 'mimi-5d20c.appspot.com',
    iosBundleId: 'com.example.archivIscae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDinjzZv4j0z-IbUz5Vvu37Phc3uREYIdA',
    appId: '1:362854059464:ios:3300d42aefabeab1c2c4fd',
    messagingSenderId: '362854059464',
    projectId: 'mimi-5d20c',
    storageBucket: 'mimi-5d20c.appspot.com',
    iosBundleId: 'com.example.archivIscae.RunnerTests',
  );
}
